name: CD Pipeline

#on:
#  workflow_run:
#    workflows: [ "CI Pipeline" ]
#    types:
#      - completed
#  push:
#     branches:
#       - main

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    permissions:
      contents: write   # needed to push commits with GITHUB_TOKEN (or use PAT)
    env:
      REPO_URL: "https://github.com/karty11/New_project.git"
      # IMAGE_TAG will be set to the github.sha of the run that triggered this workflow (workflow_run object)
      IMAGE_TAG: ${{ github.event.workflow_run.head_commit.id || github.sha }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure tools (kubectl, helm, yq, argocd CLI)
        run: |
          # kubectl
          if ! command -v kubectl >/dev/null 2>&1; then
            echo "kubectl not found - installing via azure/setup-kubectl action would be better"
            exit 1
          fi
          # helm
          if ! command -v helm >/dev/null 2>&1; then
            echo "helm not found - installing via azure/setup-helm action would be better"
            exit 1
          fi
          # yq (install if missing)
          if ! command -v yq >/dev/null 2>&1; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi
          # argocd CLI will be installed later only if needed

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
            version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.EKS_KUBECONFIG }}" > $HOME/.kube/config

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region us-west-2 --name my-eks-cluster
          # basic smoke checks
          kubectl version --short
          kubectl get nodes --no-headers

      - name: Add Argo Helm repo & update
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm || true
          helm repo update

      - name: Create argocd namespace
        run: |
          kubectl create ns argocd || echo "namespace argocd already exists"

      - name: Install/Upgrade Argo CD via Helm (idempotent)
        run: |
          # Use values file in the repo at deploy/argocd/argocd-values.yaml
          # Helm will install or upgrade depending on existing release state
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --version 7.6.9 \
            -f deploy/argocd/argocd-values.yaml \
            --wait --timeout 10m

      - name: Wait for argocd components ready (server may be ClusterIP or LB)
        run: |
          kubectl -n argocd rollout status deployment/argocd-server --timeout=120s || true
          kubectl -n argocd rollout status deployment/argocd-repo-server --timeout=120s || true
          kubectl -n argocd rollout status deployment/argocd-application-controller --timeout=120s || true

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Trigger Argo CD sync
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          if [ -n "$ARGOCD_SERVER" ] && [ -n "$ARGOCD_AUTH_TOKEN" ]; then
            argocd app sync bankapp \
              --server "$ARGOCD_SERVER" \
              --auth-token "$ARGOCD_AUTH_TOKEN" \
              --grpc-web --insecure --wait
          else
            echo "Skipping ArgoCD sync (missing secrets)"
          fi

      - name: Compute target branch
        id: branch
        run: |
          BRANCH="${GITHUB_REF_NAME:-$(jq -r '.workflow_run.head_branch' <<<"$GITHUB_EVENT_PAYLOAD")}"
          if [ -z "$BRANCH" ] || [ "$BRANCH" = "null" ]; then
            BRANCH="main"
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Apply Argo CD Application manifest
        run: |
          kubectl apply -f manifests/argocd-app-bankapp.yaml

      - name: Show created manifest (debug)
        run: |
         echo "==== manifests/argocd-app-bankapp.yaml ===="
         cat manifests/argocd-app-bankapp.yaml
         echo "==========================================="

      - name: Update Helm values.yaml with new image tag
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
            # Ensure file exists
            if [ ! -f helm/bankapp-chart/values.yaml ]; then
              echo "ERROR: helm/bankapp-chart/values.yaml not found"
              exit 1
            fi
            
            # Update image.tag (works if structure is image: { repository, tag })
            yq e -i '.image.tag = strenv(IMAGE_TAG)' helm/bankapp-chart/values.yaml
            git add helm/bankapp-chart/values.yaml
            
            if git diff --cached --quiet; then
              echo "No change to values.yaml (image tag already up-to-date)."
            else
              git commit -m "ci: bump bankapp image tag to ${IMAGE_TAG}"
              if [ -n "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
                git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
              fi
              git push origin HEAD:${BRANCH}
              echo "Pushed updated values.yaml with image tag ${IMAGE_TAG}."
            fi

      - name: Print Argo CD initial admin password (for reference)
        run: |
         echo "Argo CD initial admin password (if autogenerated):"
         kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d || echo "secret not found yet"

      
